/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:50aef6f8-7366-4adf-a78d-cd97f5695d4d",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_Qct5jVyil",
    "aws_user_pools_web_client_id": "2di51761o6hba0uh3rq90mkg77",
    "oauth": {}
};


export default awsmobile;
